version: '3.7'
services:
  backend:
    image: fsirnibc/test1:latest
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - 8080:8080
    env_file:
      - .env
  postgres:
    image: postgres:14.4
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ink
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 80:80
    depends_on:
      - postgres
